config/routes.rb
NestedForm::Application.routes.draw do
  resources :ships

  root :to => 'ships#index'

end

app/models/pilot.rb
class Pilot < ActiveRecord::Base
  belongs_to :ship

  validates :first_name,
            :presence => true,
            :length => { :maximum => 50 }

  validates :last_name,
            :presence => true,
            :length => { :maximum => 50 }

  validates :call_sign,
            :presence => true,
            :uniqueness => { :case_sensitive => false },
            :length => { :maximum => 50, :minimum => 5 }
end

app/models/ship.rb
class Ship < ActiveRecord::Base
  has_many :pilots
  accepts_nested_attributes_for :pilots,
                                :reject_if => :all_blank,
                                :allow_destroy => true

  validates_associated :pilots

  validates :name,
            :presence => true,
            :uniqueness => { :case_sensitive => false },
            :length => { :maximum => 50, :minimum => 3 }

  validates :crew,
            :presence => true,
            :inclusion => { :in => 1..5, :message => "must be between 1 and 5" }

  validates :speed,
            :presence => true,
            :inclusion => { :in => 50..200, :message => "must be between 50 and 200" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  before_action :set_ship, only: [:show, :edit, :update, :destroy]

  def index
    @ships = Ship.all
  end

  def show
  end

  def new
    @ship = Ship.new
  end

  def create
    @ship = Ship.new(ship_params)

    if @ship.save
      flash[:notice] = "The <b>#{ @ship.name }</b> ship has been saved successfully."
      redirect_to(ships_path, :notice => "The <b>#{ @ship.name }</b> ship has been saved successfully.")
    else
      render(:new, :error => @ship.errors)
    end
  end

  def edit
  end

  def update
    if @ship.update(ship_params)
      redirect_to(ships_path, :notice => "The <b>#{ @ship.name }</b> ship has been updated successfully.")
    else
      render(:edit, :error => @ship.errors)
    end
  end

  def destroy
    if @ship.destroy
      redirect_to(ships_path, :notice => "The <b>#{ @ship.name }</b> and its associated Pilots have been deleted successfully.")
    else
      redirect_to(ships_path, :notice => "The <b>#{ @ship.name }</b> could not be deleted.")
    end
  end
  
   private
    # Use callbacks to share common setup or constraints between actions.
    def set_ship
      @ship = Ship.find(params[:id])
    end
    
    # Before filters

    # Never trust parameters from the scary internet, only allow the white list through.
    def ship_params
      params.require(:ship).permit(:name, :crew, :has_astromech, :speed, :armament, pilots_attributes: [:id, :first_name, :last_name, :call_sign, :ship_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_remove_fields(name, f, options = {})
  f.hidden_field(:_destroy) + link_to(name, " ", :onclick =>"remove_fields(this); return false")
  end

  def link_to_add_fields(name, f, association, options = {})
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{ association }", :onsubmit => "return $(this.)validate();") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end

    link_to(name, " ", :onclick=>"add_fields(this, \"#{ association }\", \"#{ escape_javascript(fields) }\"); return false")
  end
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <div class="span8 alert alert-<%= name == :notice ? "success" : "error" %> fadeout">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg.html_safe, :id => "flash_#{ name }" if msg.is_a?(String) %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Starfighter Recognition Guide:  Nested Form Demo</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="span10">
          <%= render('layouts/messages') %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>

  <%= javascript_include_tag "application" %>
</html>

app/views/ships/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error alert-block">
        The form contains <%= pluralize(object.errors.count, "error") %>.
        <ul>
          <% object.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

app/views/ships/_form.html.erb
<%= form_for(@ship, :html => {:class => "form form-horizontal" }) do |f| %>
    <fieldset>
      <legend><%= "#{ @ship.name } " unless @ship.name.nil?  %>Ship Information</legend>
      <%= render('error_messages', :object => f.object) %>
      <div class="control-group">
        <%= f.label(:name, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:name, :class => "input-xlarge") %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label(:crew, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:crew, :class => "input-xlarge") %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label(:has_astromech, :class => "control-label") %>
        <div class="controls">
          <%= f.check_box(:has_astromech, :class => "checkbox") %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label(:speed, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:speed, :class => "input-xlarge") %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label(:armament, :class => "control-label") %>
        <div class="controls">
          <%= f.text_area(:armament, :class => "input-xlarge", :rows => "3") %>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Pilots <%= "That Fly the  #{ @ship.name }" unless @ship.name.blank? %></legend>
      <%= render('pilots_table', :f => f) %>
      <%= link_to_add_fields("Add a Pilot", f, :pilots, :class => "btn btn-primary", :title => "Add a new Pilot to the list of Pilots that fly this Ship.") %>
      <p></p>
    </fieldset>

    <div class="modal-footer">
      <%= f.submit("Save", :class => "btn btn-primary", :title => "Save the changes to this Ship.") %>
      <%= link_to("Cancel", ships_path, :confirm => "Are you sure you want to cancel?  Any changes will be lost.", :class => "btn btn-inverse", :title => "Cancel the changes and return to the Home page.") %>
    </div>
<% end %>

app/views/ships/_pilot_fields.html.erb
<div id="new-pilot-fields" class="modal fade" data-backdrop="static">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Add a Pilot<%= " to the #{ @ship.name } Pilot Roster" unless @ship.name.nil? %></h3>
  </div>
  <div class="modal-body">
    <fieldset>
      <div class="control-group">
        <%= f.label(:first_name, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:first_name, :class => "input-xlarge field", :data => { :validation => "required validate_max_length length50", "validation-error-msg" => "First Name is required and cannot be longer than 50 characters." }) %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label(:last_name, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:last_name, :class => "input-xlarge field", :data => { :validation => "required validate_max_length length50", "validation-error-msg" => "Last Name is required and cannot be longer than 50 characters." }) %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label(:call_sign, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:call_sign, :class => "input-xlarge field", :data => { :validation => "required validate_length length5-50", "validation-error-msg" => "Call Sign is required and cannot be must be between 5 and 50 characters." }) %>
        </div>
      </div>
      <%= f.hidden_field(:_destroy, :class => "field") %>
    </fieldset>
  </div>
  <div class="modal-footer">
    <button id="addButton" type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="true" title="Add this Pilot to the list of Pilots that are assigned to this Ship.">Add</button>
    <button id="cancelButton" type="button" class="btn btn-inverse" data-dismiss="modal" aria-hidden="true" title="Close this screen without adding the Pilot to the list.">Cancel</button>
  </div>
</div>

<script type="text/javascript">
  pilotFieldsUI.init();
</script>

app/views/ships/_pilots_display.html.erb
<table id="pilots-display-table" class="table table-hover table-striped">
  <thead>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Call Sign</th>
  </thead>
  <tbody>
      <% @ship.pilots.each do |pilot| %>
          <tr class="fields">
            <td><%= pilot.first_name %></td>
            <td><%= pilot.last_name %></td>
            <td><%= pilot.call_sign %></td>
          </tr>
      <% end %>
  </tbody>
</table>

app/views/ships/_pilots_table.html.erb
<table id="pilots-table" class="table table-hover table-striped">
  <thead>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Call Sign</th>
  <th></th>
  </thead>
  <tbody>
    <%= f.fields_for(:pilots) do |pilots_form| %>
      <tr class="fields">
        <td><%= pilots_form.text_field(:first_name) %></td>
        <td><%= pilots_form.text_field(:last_name) %></td>
        <td><%= pilots_form.text_field(:call_sign) %></td>
        <%# if current_page?(new_ship_path) || current_page?(edit_ship_path) %>
            <td>
              <%= link_to_remove_fields('<i class="icon-remove"></i>'.html_safe, pilots_form, :title => "Delete this Pilot.") %>
            </td>
        <%# end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ships/edit.html.erb
<h1>Editing <%= @ship.name %></h1>
<%= render('form') %>

app/views/ships/index.html.erb
<h2>Starfighters of the Star Wars Universe</h2>
<table class="table table-hover table-striped">
  <thead>
    <th>Name</th>
    <th>Speed</th>
    <th>Crew</th>
    <th>Has Astromech Droid</th>
    <th>Armament</th>
    <th colspan="3"></th>
  </thead>
  <tbody>
    <% @ships.each do |ship| %>
      <tr>
        <td><%= ship.name %></td>
        <td><%= ship.speed %></td>
        <td><%= ship.crew %></td>
        <td><%= '<i class="icon-ok"/>'.html_safe if ship.has_astromech %></td>
        <td><%= ship.armament %></td>
        <td><%= link_to('<i class="icon-eye-open"/>'.html_safe, ship, :title => "View #{ ship.name }.")  %></td>
        <td><%= link_to('<i class="icon-edit"/>'.html_safe, edit_ship_path(ship), :title => "Edit #{ ship.name }.") %></td>
        <td><%= link_to('<i class="icon-remove"/>'.html_safe, ship, :method => :delete, :confirm => "Are you sure you want to permanently delete the #{ ship.name } and all its associated Pilots?", :title => "Delete #{ ship.name }.") %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to("Add a Ship", new_ship_path, :class => "btn btn-primary", :title => "Add a new Ship to the Starfighter Recognition database.") %>

app/views/ships/new.html.erb
<h1>Add a Ship to the Recognition Guide</h1>
<%= render('form') %>

app/views/ships/show.html.erb
<h1>Viewing <%= @ship.name %></h1>
<div class="form-horizontal">
<fieldset>
  <legend><%= @ship.name %> Ship Information</legend>
  <div class="control-group">
    <label class="control-label">Name:</label>
    <div class="controls">
      <label class="radio inline"><strong><%= @ship.name %></strong></label>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Crew:</label>
    <div class="controls">
      <span class="radio inline"><strong><%= @ship.crew %></strong></span>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Speed:</label>
    <div class="controls">
      <span class="radio inline"><strong><%= @ship.speed %></strong></span>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Has Astromech:</label>
    <div class="controls">
      <span class="radio inline"><strong><%= @ship.has_astromech ? "Yes" : "No" %></strong></span>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Armament:</label>
    <div class="controls">
      <span class="radio inline"><strong><%= @ship.armament %></strong></span>
    </div>
  </div>
</fieldset>

<fieldset>
  <legend>Pilots Assigned to This Type of Ship</legend>
  <%= render('pilots_display') %>
</fieldset>

  <div class="modal-footer">
    <%= link_to("Edit", edit_ship_path(@ship), :class => "btn btn-primary", :title => "Edit #{ @ship.name }.") %>
    <%= link_to("Back to Home", ships_path, :class => "btn btn-inverse", :title => "Return to the Home page.") %>
  </div>
</div>